const esercizi = [
  {
    livello: "principiante",
    schede: [
      {
        nome: "A",
        esercizi: [
          {
            esercizio: "Squat",
            link: "https://youtu.be/-bJIpOq-LWk?feature=shared",
            set: "3 x 12",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Lunges",
            link: "https://youtu.be/9gglI77Kzq8?feature=shared",
            set: "3 x 12",
            note: "",
            rest: "1'x gamba",
          },
          {
            esercizio: "Let Machine",
            link: "https://youtu.be/AkRfptSYvLo?feature=shared",
            set: "3 x 12",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Alzate Laterali",
            link: "https://www.youtube.com/watch?v=7xe8l-8zBOo",
            set: "3 x 12",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Crunch",
            link: "https://www.youtube.com/watch?v=Iep9ffXKQHw",
            set: "3 x 15",
            note: "",
            rest: "1' 30''",
          },
          {
            esercizio: "Plank",
            link: "https://www.youtube.com/watch?v=WUk9rd-rI7Y",
            set: "3 x 30''",
            note: "",
            rest: "1'",
          },
        ],
      },
      {
        nome: "B",
        esercizi: [
          {
            esercizio: "Deadlift DB",
            link: "https://www.youtube.com/watch?v=plb5jEO4Unw",
            set: "3 x 12",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Pulley",
            link: "https://www.youtube.com/watch?v=HIrH8XOhbrc",
            set: "3 x 12",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Military Press DB",
            link: "https://www.youtube.com/watch?v=0rChzYPyuYI",
            set: "3 x 10",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Shrugs",
            link: "https://www.youtube.com/watch?v=yqzRYcOMx2Q",
            set: "3 x 10",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "French Press DB",
            link: "https://www.youtube.com/watch?v=vS_lKYyyWkA",
            set: "3 x 12",
            note: "",
            rest: "1' 30''",
          },
          {
            esercizio: "Side Plank",
            link: "https://www.youtube.com/watch?v=_R389Jk0tIo",
            set: "3 x 30''",
            note: "",
            rest: "30''x lato",
          },
        ],
      },
      {
        nome: "C",
        esercizi: [
          {
            esercizio: "Bench Press DB",
            link: "https://www.youtube.com/watch?v=AduT4Eq-iP0",
            set: "3 x 12",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Chest Fly DB",
            link: "https://www.youtube.com/watch?v=Nhvz9EzdJ4U",
            set: "3 x 12",
            note: "",
            rest: "1'x gamba",
          },
          {
            esercizio: "Curl DB",
            link: "https://www.youtube.com/watch?v=HnHuhf4hEWY",
            set: "3 x 10",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Hummer Curl",
            link: "https://www.youtube.com/watch?v=CFBZ4jN1CMI",
            set: "3 x 12",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Bicycle Crunch",
            link: "https://www.youtube.com/watch?v=cbKIDZ_XyjY",
            set: "3 x 15",
            note: "",
            rest: "1' 30''",
          },
          {
            esercizio: "Calf Machine",
            link: "https://www.youtube.com/watch?v=HSGjUouQZCQ",
            set: "3 x 12",
            note: "",
            rest: "1'",
          },
        ],
      },
    ],
  },
  {
    livello: "intermedio",
    schede: [
      {
        nome: "A",
        esercizi: [
          {
            esercizio: "Squat",
            link: "https://youtu.be/-bJIpOq-LWk?feature=shared",
            set: "4 x 8",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Lunges",
            link: "https://youtu.be/9gglI77Kzq8?feature=shared",
            set: "3 x 8",
            note: "",
            rest: "1'x gamba",
          },
          {
            esercizio: "Leg Curl",
            link: "https://www.youtube.com/watch?v=SiwJ_T62l9c",
            set: "3 x 10",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Let Machine",
            link: "https://youtu.be/AkRfptSYvLo?feature=shared",
            set: "4 x 8",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Chin Up",
            link: "https://www.youtube.com/watch?v=xBzKgvYBxI4",
            set: "4 x 8",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Crunch",
            link: "https://www.youtube.com/watch?v=Iep9ffXKQHw",
            set: "4 x max",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "Plank",
            link: "https://www.youtube.com/watch?v=WUk9rd-rI7Y",
            set: "3 x max",
            note: "",
            rest: "1'",
          },
        ],
      },
      {
        nome: "B",
        esercizi: [
          {
            esercizio: "Deadlift BB",
            link: "https://www.youtube.com/watch?v=CN_7cz3P-1U",
            set: "4 x 8",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Pulley",
            link: "https://www.youtube.com/watch?v=HIrH8XOhbrc",
            set: "4 x 8",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Military Press BB",
            link: "https://www.youtube.com/watch?v=IuzRCN6eG6Y",
            set: "4 x 10",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Shrugs",
            link: "https://www.youtube.com/watch?v=yqzRYcOMx2Q",
            set: "3 x 10",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "French Press Ez Bar",
            link: "https://www.youtube.com/watch?v=zQQQ444P588",
            set: "3 x 10",
            note: "",
            rest: "1' 30''",
          },
          {
            esercizio: "Dip con Zavorra",
            link: "https://www.youtube.com/watch?v=rXeyNuQ58wU",
            set: "4 x 8",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Side Plank",
            link: "https://www.youtube.com/watch?v=_R389Jk0tIo",
            set: "3 x max'",
            note: "",
            rest: "30''x lato",
          },
        ],
      },
      {
        nome: "C",
        esercizi: [
          {
            esercizio: "Bench Press BB",
            link: "https://www.youtube.com/watch?v=SCVCLChPQFY",
            set: "4 x 8",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Peck Deck",
            link: "https://www.youtube.com/watch?v=lSV3-8mlUnc",
            set: "3 x 12",
            note: "",
            rest: "1'x 30'' ",
          },
          {
            esercizio: "Curl DB panca inclinata",
            link: "https://www.youtube.com/watch?v=a1VJvIFPObk",
            set: "3 x 10",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Hummer Curl",
            link: "https://www.youtube.com/watch?v=CFBZ4jN1CMI",
            set: "4 x 10",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Bicycle Crunch",
            link: "https://www.youtube.com/watch?v=cbKIDZ_XyjY",
            set: "4 x max",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "Calf Machine",
            link: "https://www.youtube.com/watch?v=HSGjUouQZCQ",
            set: "3 x 20",
            note: "",
            rest: "1'",
          },
        ],
      },
    ],
  },
  {
    livello: "avanzato",
    schede: [
      {
        nome: "A",
        esercizi: [
          {
            esercizio: "Squat",
            link: "https://youtu.be/-bJIpOq-LWk?feature=shared",
            set: "4 x 10/8/6/4",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Lunges Deficit",
            link: "https://youtu.be/9gglI77Kzq8?feature=shared",
            set: "3 x 8/10",
            note: "",
            rest: "1'x gamba",
          },
          {
            esercizio: "Leg Curl",
            link: "https://www.youtube.com/watch?v=SiwJ_T62l9c",
            set: "4 x 8",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "Let Machine",
            link: "https://youtu.be/AkRfptSYvLo?feature=shared",
            set: "4 x 8",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Row Barbell",
            link: "https://www.youtube.com/watch?v=9Gf-Ourup_k",
            set: "3 x Max",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Chin Up",
            link: "https://www.youtube.com/watch?v=xBzKgvYBxI4",
            set: "4 x max",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Crunch",
            link: "https://www.youtube.com/watch?v=Iep9ffXKQHw",
            set: "5 x max",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "Plank",
            link: "https://www.youtube.com/watch?v=WUk9rd-rI7Y",
            set: "3 x 1'/1'30''",
            note: "",
            rest: "1'",
          },
        ],
      },
      {
        nome: "B",
        esercizi: [
          {
            esercizio: "Deadlift BB",
            link: "https://www.youtube.com/watch?v=CN_7cz3P-1U",
            set: "4 x 10/8/6/4",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Pulley",
            link: "https://www.youtube.com/watch?v=HIrH8XOhbrc",
            set: "4 x Max",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Military Press BB",
            link: "https://www.youtube.com/watch?v=IuzRCN6eG6Y",
            set: "5 x 6",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Shrugs ",
            link: "https://www.youtube.com/watch?v=yqzRYcOMx2Q",
            set: "3 x 8",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "Lateral Raises ",
            link: "https:/www.youtube.com/watch?v=axW4JQUOlFA",
            set: "3 x 8",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "French Press Ez Bar",
            link: "https://www.youtube.com/watch?v=zQQQ444P588",
            set: "4 x 8",
            note: "",
            rest: "1' 30''",
          },
          {
            esercizio: "Dip con Zavorra",
            link: "https://www.youtube.com/watch?v=rXeyNuQ58wU",
            set: "4 x max",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "Side Plank",
            link: "https://www.youtube.com/watch?v=_R389Jk0tIo",
            set: "4 x 45''/1''",
            note: "",
            rest: "30''x lato",
          },
        ],
      },
      {
        nome: "C",
        esercizi: [
          {
            esercizio: "Bench Press BB",
            link: "https://www.youtube.com/watch?v=SCVCLChPQFY",
            set: "4 x 10/8/6/4",
            note: "",
            rest: "2'",
          },
          {
            esercizio: "Peck Deck",
            link: "https://www.youtube.com/watch?v=lSV3-8mlUnc",
            set: "4 x 8",
            note: "",
            rest: "1'x gamba",
          },
          {
            esercizio: "Curl DB panca inclinata",
            link: "https://www.youtube.com/watch?v=a1VJvIFPObk",
            set: "4 x 10",
            note: "",
            rest: "1'30'' ",
          },
          {
            esercizio: "Hummer Curl",
            link: "https://www.youtube.com/watch?v=CFBZ4jN1CMI",
            set: "4 x 8",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "PushDown",
            link: "https://www.youtube.com/watch?v=5XjpecNSJbg",
            set: "4 x 8",
            note: "",
            rest: "1'30''",
          },
          {
            esercizio: "Bicycle Crunch",
            link: "https://www.youtube.com/watch?v=cbKIDZ_XyjY",
            set: "5 x max",
            note: "",
            rest: "1'",
          },
          {
            esercizio: "Calf Machine",
            link: "https://www.youtube.com/watch?v=HSGjUouQZCQ",
            set: "4 x 12",
            note: "",
            rest: "1'",
          },
        ],
      },
    ],
  },
];
export default esercizi;
